# Generated by Django 5.0.6 on 2024-06-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_userprofile_bio_createpost_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['created_at']},
        ),
    ]
