# Generated by Django 5.0.6 on 2024-06-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_createpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['-created_at']},
        ),
    ]
