# Generated by Django 5.0.3 on 2024-06-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_createpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='content',
            field=models.TextField(),
        ),
    ]
