# Generated by Django 5.0.3 on 2024-06-16 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_createpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
